-- Ganeshwaram -- full menu, transcribed from the seven printed pages.
--
-- Same shape as backend/seeds/jawahar_menu.sql, and the reasoning in that file's header applies
-- here unchanged: it touches only the menu, it refuses to run against the wrong database, and it
-- is a SYNC rather than an append -- anything this restaurant has that is not in this file is
-- archived, not deleted, because order_item.menu_item_id is ON DELETE RESTRICT (D8).
--
-- Preserved across a re-run, because this file is not the authority on any of it:
--   * is_available -- the "we ran out" toggle staff flip during service
--   * rating_count / rating_sum -- the review aggregate (migration 016)
--   * image_url / image_key -- photos uploaded through the admin app (D15)
--
-- WHAT IS DIFFERENT FROM JAWAHAR
--
-- 1. EVERY DISH IS VEGETARIAN. The restaurant is a pure-veg house -- its own logo reads
--    "veg food · sweets · snacks" -- and there is no meat or egg anywhere on the seven pages. So
--    food_type is 'veg' on all 357 rows. That is a fact off the card, not an assumption, and it
--    is worth stating because a single stray 'non_veg' here would be a serious error in a
--    restaurant whose customers choose it precisely for this.
--
-- 2. THE PRINTED ASTERISK IS CARRIED INTO THE DESCRIPTIONS. The menu footer defines it as
--    "available without onion and garlic also", which in this market is an ordering constraint
--    rather than a footnote -- it is why a satvik or Jain diner can eat here at all. The schema
--    has no column for it, so the dishes that carry it say so in their own description where a
--    diner will actually read it. If that ever becomes a filter, it should become a column.
--
-- 3. TIMED AND SEASONAL ITEMS SAY SO. Breakfast is 9:30-11:30 am (last order 11:00), tandoor
--    items may be unavailable 4-6 pm, and saag, gajar halwa and moong dal halwa are winter only.
--    All of that is in the description rather than enforced, because the schema has no opening
--    hours and inventing one here would be worse than telling the diner plainly.
--
-- TRANSCRIPTION NOTES -- read before running:
--   * The DESSERTS page is the one photographed at an angle, and its two price columns sit
--     visually offset from their names. The reading here follows each column top to bottom and is
--     self-consistent, but the sweets counter is where a wrong price costs real money. Have
--     somebody check that section against the card before the first service.
--   * Mineral Water and Soft Drink (250 ml / 750 ml) are priced "MRP" on the board. price_minor
--     is NOT NULL and a guessed figure would mis-bill a diner, so they are left out -- the lines
--     are ready to uncomment at the foot of the item list once a figure is decided.
--   * Items sold "(per kg)" are priced per kilogram. The cart multiplies quantity by price, so a
--     diner ordering 2 is billed for 2 kg. That is correct for a mithai counter but worth knowing
--     before somebody reports it as a bug.
--   * spice_level and prep_time_mins are NOT on the board. They are house defaults, set so the
--     diner card renders fully; the kitchen should correct them.
--
-- USAGE
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f backend/seeds/ganeshwaram_menu.sql
--   make seed SEED_FILE=backend/seeds/ganeshwaram_menu.sql
--
-- The whole file is one transaction. A failure anywhere leaves the live menu untouched.

BEGIN;

-- ---------------------------------------------------------------------------
-- Target restaurant. THE ONE LINE TO EDIT.
-- ---------------------------------------------------------------------------
CREATE TEMP TABLE gw_target (slug TEXT NOT NULL) ON COMMIT DROP;
INSERT INTO gw_target (slug) VALUES ('ganeshwaram');

DO $guard$
DECLARE
    target TEXT := (SELECT slug FROM gw_target);
    found  INT;
BEGIN
    SELECT count(*) INTO found FROM restaurant WHERE slug = target;
    IF found = 0 THEN
        RAISE EXCEPTION
            'no restaurant with slug %. Set it at the top of this file; the menu was NOT changed.',
            target;
    END IF;
END
$guard$;

CREATE TEMP TABLE gw_category (
    uid TEXT, name TEXT, description TEXT, sort_order INT
) ON COMMIT DROP;

INSERT INTO gw_category (uid, name, description, sort_order) VALUES
    ('cat_gw_breakfast'      , 'Happy Breakfast'                   , 'Served 9:30–11:30 am, last order 11:00 am',   10),
    ('cat_gw_chandni'        , 'Chandni Chowk Ke Kisse'            , 'Chaat and street snacks',   20),
    ('cat_gw_south'          , 'South Indian'                      , NULL,   30),
    ('cat_gw_soups'          , 'Soups'                             , NULL,   40),
    ('cat_gw_grilled'        , 'Grilled Specialities'              , 'From the tandoor',   50),
    ('cat_gw_chinese'        , 'Chinese Shinese'                   , NULL,   60),
    ('cat_gw_alacarte'       , 'Separate Menu (À la Carte)'        , 'Curries, dal and paneer',   70),
    ('cat_gw_rice'           , 'Rice & Raita'                      , NULL,   80),
    ('cat_gw_meals'          , 'Rice / Noodles Meals'              , 'One-plate meals',   90),
    ('cat_gw_breads'         , 'Breads'                            , 'From the tandoor',  100),
    ('cat_gw_thali'          , 'Set Menu (Thalis)'                 , 'A full plate, one price',  110),
    ('cat_gw_platters'       , 'Platters'                          , 'Built to share',  120),
    ('cat_gw_sizzlers'       , 'Sizzlers'                          , 'Served on a hot plate',  130),
    ('cat_gw_continental'    , 'Pizzas, Pasta, Burgers & Salads'   , NULL,  140),
    ('cat_gw_addon'          , 'Extra (Add On)'                    , NULL,  150),
    ('cat_gw_beverages'      , 'Beverages'                         , 'Thanda Garam',  160),
    ('cat_gw_shakes'         , 'Shakes'                            , NULL,  170),
    ('cat_gw_mocktails'      , 'Mocktails'                         , NULL,  180),
    ('cat_gw_icecream'       , 'Ice Creams'                        , NULL,  190),
    ('cat_gw_desserts'       , 'Desserts'                          , 'From the mithai counter',  200)
;

-- Prices are integer paise (D7): 29900 is Rs 299.00.
-- food_type is not a column here: every row is 'veg', applied in the INSERT below.
CREATE TEMP TABLE gw_item (
    uid TEXT, category_uid TEXT, name TEXT, description TEXT,
    price_minor BIGINT, spice_level TEXT, is_bestseller BOOLEAN,
    prep_time_mins INT, sort_order INT
) ON COMMIT DROP;

INSERT INTO gw_item (uid, category_uid, name, description, price_minor,
                     spice_level, is_bestseller, prep_time_mins, sort_order) VALUES

    -- Happy Breakfast
    ('itm_gw_jalebi_100_g'                          , 'cat_gw_breakfast'    , 'Jalebi (100 g)'                                    ,
     'Coiled, fried and soaked in syrup. Sold by weight.',
       5500, NULL    , FALSE,  10,   10),
    ('itm_gw_vada_pav'                              , 'cat_gw_breakfast'    , 'Vada Pav'                                          ,
     'Spiced potato fritter in a pav with dry garlic chutney.',
       5500, 'medium', TRUE ,  10,   20),
    ('itm_gw_emarti_100_g'                          , 'cat_gw_breakfast'    , 'Emarti (100 g)'                                    ,
     'Urad dal spirals in saffron syrup, denser than jalebi.',
       5600, NULL    , FALSE,  10,   30),
    ('itm_gw_1_samosa_1_tea'                        , 'cat_gw_breakfast'    , '1 Samosa + 1 Tea'                                  ,
     'The standard morning pairing.',
       5900, 'mild'  , TRUE ,   8,   40),
    ('itm_gw_1_samosa_1_hot_coffee'                 , 'cat_gw_breakfast'    , '1 Samosa + 1 Hot Coffee'                           ,
     'Samosa with a hot filter coffee.',
       6900, 'mild'  , FALSE,   8,   50),
    ('itm_gw_cold_sandwich'                         , 'cat_gw_breakfast'    , 'Cold Sandwich'                                     ,
     'Vegetables and chutney, served cold.',
       6900, 'mild'  , FALSE,  10,   60),
    ('itm_gw_2_dal_kachori_with_aloo_sabji'         , 'cat_gw_breakfast'    , '2 Dal Kachori With Aloo Sabji'                     ,
     'Two lentil kachoris with a thin potato curry.',
       7500, 'medium', TRUE ,  12,   70),
    ('itm_gw_dahi_idli'                             , 'cat_gw_breakfast'    , 'Dahi Idli'                                         ,
     'Steamed idli set in sweetened curd.',
       9900, 'mild'  , FALSE,  12,   80),
    ('itm_gw_moong_dal_cheela_plain'                , 'cat_gw_breakfast'    , 'Moong Dal Cheela (Plain)'                          ,
     'Thin lentil pancake, griddled.',
       9900, 'mild'  , FALSE,  12,   90),
    ('itm_gw_paratha_with_curd_aloo'                , 'cat_gw_breakfast'    , 'Paratha With Curd (Aloo)'                          ,
     'Potato-stuffed paratha with curd and pickle.',
       9900, 'medium', TRUE ,  15,  100),
    ('itm_gw_paratha_with_curd_onion'               , 'cat_gw_breakfast'    , 'Paratha With Curd (Onion)'                         ,
     'Onion-stuffed paratha with curd and pickle.',
       9900, 'medium', FALSE,  15,  110),
    ('itm_gw_veg_cheese_grilled_sandwich'           , 'cat_gw_breakfast'    , 'Veg & Cheese Grilled Sandwich'                     ,
     'Grilled with vegetables and cheese.',
       9900, 'mild'  , FALSE,  12,  120),
    ('itm_gw_idli_with_sambar'                      , 'cat_gw_breakfast'    , 'Idli With Sambar'                                  ,
     'Steamed rice cakes with sambar and chutney.',
      10900, 'mild'  , FALSE,  12,  130),
    ('itm_gw_matar_kulcha'                          , 'cat_gw_breakfast'    , 'Matar Kulcha'                                      ,
     'White peas with a griddled kulcha.',
      10900, 'medium', FALSE,  12,  140),
    ('itm_gw_paratha_with_curd_mix'                 , 'cat_gw_breakfast'    , 'Paratha With Curd (Mix)'                           ,
     'Mixed stuffing, with curd and pickle.',
      10900, 'medium', FALSE,  15,  150),
    ('itm_gw_bedmi_puri_sabji_with_raita'           , 'cat_gw_breakfast'    , 'Bedmi Puri Sabji With Raita'                       ,
     'Urad-stuffed puris with potato sabji and raita.',
      11900, 'medium', TRUE ,  15,  160),
    ('itm_gw_dosa_plain'                            , 'cat_gw_breakfast'    , 'Dosa (Plain)'                                      ,
     'Crisp rice-and-lentil crepe with sambar and chutney.',
      11900, 'mild'  , FALSE,  15,  170),
    ('itm_gw_moong_dal_cheela_masala'               , 'cat_gw_breakfast'    , 'Moong Dal Cheela (Masala)'                         ,
     'Lentil pancake with a spiced filling.',
      11900, 'medium', FALSE,  15,  180),
    ('itm_gw_pav_bhaji'                             , 'cat_gw_breakfast'    , 'Pav Bhaji'                                         ,
     'Mashed vegetable curry with buttered pav.',
      11900, 'medium', TRUE ,  15,  190),
    ('itm_gw_puri_chole_with_raita'                 , 'cat_gw_breakfast'    , 'Puri Chole With Raita'                             ,
     'Puris with chickpea curry and raita.',
      11900, 'medium', FALSE,  15,  200),
    ('itm_gw_puri_sabji_with_raita'                 , 'cat_gw_breakfast'    , 'Puri Sabji With Raita'                             ,
     'Puris with potato sabji and raita.',
      11900, 'medium', FALSE,  15,  210),
    ('itm_gw_chole_bhature_with_raita'              , 'cat_gw_breakfast'    , 'Chole Bhature With Raita'                          ,
     'Two bhature with chickpea curry and raita.',
      13900, 'medium', TRUE ,  18,  220),
    ('itm_gw_dosa_masala'                           , 'cat_gw_breakfast'    , 'Dosa (Masala)'                                     ,
     'Dosa filled with spiced potato.',
      13900, 'medium', TRUE ,  15,  230),
    ('itm_gw_uttapam_onion_tomato_mix'              , 'cat_gw_breakfast'    , 'Uttapam (Onion / Tomato / Mix)'                    ,
     'Thick savoury pancake, griddled with toppings.',
      16900, 'mild'  , FALSE,  15,  240),

    -- Chandni Chowk Ke Kisse
    ('itm_gw_samosa_1_pc'                           , 'cat_gw_chandni'      , 'Samosa (1 pc)'                                     ,
     'Spiced potato and pea filling, fried.',
       2300, 'medium', TRUE ,   8,   10),
    ('itm_gw_dal_kachori_1_pc'                      , 'cat_gw_chandni'      , 'Dal Kachori (1 pc)'                                ,
     'Flaky pastry with a spiced lentil filling.',
       2500, 'medium', FALSE,   8,   20),
    ('itm_gw_bread_pakora_1_pc'                     , 'cat_gw_chandni'      , 'Bread Pakora (1 pc)'                               ,
     'Battered and fried stuffed bread.',
       3000, 'medium', FALSE,  10,   30),
    ('itm_gw_paneer_pakora_1_pc'                    , 'cat_gw_chandni'      , 'Paneer Pakora (1 pc)'                              ,
     'Cottage cheese in gram-flour batter.',
       3500, 'mild'  , FALSE,  10,   40),
    ('itm_gw_1_samosa_1_tea_2'                      , 'cat_gw_chandni'      , '1 Samosa + 1 Tea'                                  ,
     'The standard pairing, any time of day.',
       5900, 'mild'  , FALSE,   8,   50),
    ('itm_gw_pani_puri_aata_6_pcs'                  , 'cat_gw_chandni'      , 'Pani Puri — Aata (6 pcs)'                          ,
     'Wheat puris with spiced water.',
       5900, 'hot'   , TRUE ,   8,   60),
    ('itm_gw_pani_puri_suji_6_pcs'                  , 'cat_gw_chandni'      , 'Pani Puri — Suji (6 pcs)'                          ,
     'Semolina puris with spiced water.',
       5900, 'hot'   , FALSE,   8,   70),
    ('itm_gw_vada_pav_2'                            , 'cat_gw_chandni'      , 'Vada Pav'                                          ,
     'Potato fritter in a pav with dry garlic chutney.',
       6000, 'medium', FALSE,  10,   80),
    ('itm_gw_1_samosa_1_cappuccino'                 , 'cat_gw_chandni'      , '1 Samosa + 1 Cappuccino'                           ,
     'Samosa with a cappuccino.',
       7900, 'mild'  , FALSE,   8,   90),
    ('itm_gw_2_dal_kachori_with_aloo_sabji_2'       , 'cat_gw_chandni'      , '2 Dal Kachori With Aloo Sabji'                     ,
     'Two kachoris with a thin potato curry.',
       8500, 'medium', FALSE,  12,  100),
    ('itm_gw_aloo_tikki_with_chutney_1_pc'          , 'cat_gw_chandni'      , 'Aloo Tikki With Chutney (1 pc)'                    ,
     'Griddled potato patty with chutneys.',
       8500, 'medium', FALSE,  10,  110),
    ('itm_gw_samosa_chaat'                          , 'cat_gw_chandni'      , 'Samosa Chaat'                                      ,
     'Crushed samosa under chole, curd and chutney.',
       9500, 'medium', TRUE ,  10,  120),
    ('itm_gw_bhel_puri'                             , 'cat_gw_chandni'      , 'Bhel Puri'                                         ,
     'Puffed rice tossed with chutney and sev.',
       9900, 'medium', FALSE,   8,  130),
    ('itm_gw_aloo_tikki_with_chutney_2_pcs'         , 'cat_gw_chandni'      , 'Aloo Tikki With Chutney (2 pcs)'                   ,
     'Two potato patties with chutneys.',
      10500, 'medium', FALSE,  10,  140),
    ('itm_gw_bhalla_papdi'                          , 'cat_gw_chandni'      , 'Bhalla Papdi'                                      ,
     'Lentil dumplings and papdi in curd.',
      13500, 'mild'  , FALSE,  10,  150),
    ('itm_gw_dahi_bhalla'                           , 'cat_gw_chandni'      , 'Dahi Bhalla'                                       ,
     'Soft lentil dumplings in sweetened curd.',
      13500, 'mild'  , TRUE ,  10,  160),
    ('itm_gw_dahi_puri_6_pcs'                       , 'cat_gw_chandni'      , 'Dahi Puri (6 pcs)'                                 ,
     'Filled puris topped with curd and chutney.',
      13500, 'mild'  , FALSE,  10,  170),
    ('itm_gw_matar_kulcha_2'                        , 'cat_gw_chandni'      , 'Matar Kulcha'                                      ,
     'Spiced white peas with a griddled kulcha.',
      13500, 'medium', FALSE,  12,  180),
    ('itm_gw_papdi_chaat'                           , 'cat_gw_chandni'      , 'Papdi Chaat'                                       ,
     'Crisp papdi with curd, chutney and potato.',
      13500, 'medium', FALSE,  10,  190),
    ('itm_gw_aloo_tikki_with_dahi_or_chole'         , 'cat_gw_chandni'      , 'Aloo Tikki With Dahi Or Chole'                     ,
     'Potato patty topped with curd or chickpeas.',
      14000, 'medium', FALSE,  12,  200),
    ('itm_gw_mix_veg_pakora_11_pcs'                 , 'cat_gw_chandni'      , 'Mix Veg Pakora (11 pcs)'                           ,
     'A plate of mixed vegetable fritters.',
      14500, 'medium', FALSE,  12,  210),
    ('itm_gw_paneer_pakora_5_pcs'                   , 'cat_gw_chandni'      , 'Paneer Pakora (5 pcs)'                             ,
     'A plate of cottage cheese fritters.',
      14500, 'mild'  , FALSE,  12,  220),
    ('itm_gw_raj_kachori'                           , 'cat_gw_chandni'      , 'Raj Kachori'                                       ,
     'A large kachori filled with curd, chutney and sprouts.',
      14500, 'medium', TRUE ,  12,  230),
    ('itm_gw_aloo_tikki_with_dahi_chole'            , 'cat_gw_chandni'      , 'Aloo Tikki With Dahi & Chole'                      ,
     'Potato patty with both curd and chickpeas.',
      15900, 'medium', FALSE,  12,  240),
    ('itm_gw_bedmi_puri_sabji_with_raita_2'         , 'cat_gw_chandni'      , 'Bedmi Puri Sabji With Raita'                       ,
     'Urad-stuffed puris with sabji and raita.',
      16900, 'medium', FALSE,  15,  250),
    ('itm_gw_chole_bhature_with_raita_2'            , 'cat_gw_chandni'      , 'Chole Bhature With Raita'                          ,
     'Two bhature with chickpea curry and raita.',
      16900, 'medium', TRUE ,  18,  260),
    ('itm_gw_pav_bhaji_2'                           , 'cat_gw_chandni'      , 'Pav Bhaji'                                         ,
     'Mashed vegetable curry with buttered pav.',
      16900, 'medium', FALSE,  15,  270),
    ('itm_gw_puri_chole_with_raita_2'               , 'cat_gw_chandni'      , 'Puri Chole With Raita'                             ,
     'Puris with chickpea curry and raita.',
      16900, 'medium', FALSE,  15,  280),
    ('itm_gw_puri_sabji_with_raita_2'               , 'cat_gw_chandni'      , 'Puri Sabji With Raita'                             ,
     'Puris with potato sabji and raita.',
      16900, 'medium', FALSE,  15,  290),
    ('itm_gw_dhokla_per_kg'                         , 'cat_gw_chandni'      , 'Dhokla (per kg)'                                   ,
     'Steamed gram-flour cake, tempered. Sold by weight.',
      26000, 'mild'  , FALSE,  10,  300),

    -- South Indian
    ('itm_gw_dahi_idli_2'                           , 'cat_gw_south'        , 'Dahi Idli'                                         ,
     'Steamed idli set in sweetened curd. Can be made without onion or garlic — ask when ordering.',
      13500, 'mild'  , FALSE,  12,   10),
    ('itm_gw_dahi_vada'                             , 'cat_gw_south'        , 'Dahi Vada'                                         ,
     'Fried lentil dumplings in curd. Can be made without onion or garlic — ask when ordering.',
      13500, 'mild'  , FALSE,  12,   20),
    ('itm_gw_idli_with_sambar_2'                    , 'cat_gw_south'        , 'Idli With Sambar'                                  ,
     'Steamed rice cakes, sambar and chutney. Can be made without onion or garlic — ask when ordering.',
      13900, 'mild'  , FALSE,  12,   30),
    ('itm_gw_1_idli_1_vada_with_sambar'             , 'cat_gw_south'        , '1 Idli & 1 Vada With Sambar'                       ,
     'One of each, with sambar and chutney.',
      14500, 'mild'  , FALSE,  12,   40),
    ('itm_gw_vada_with_sambar'                      , 'cat_gw_south'        , 'Vada With Sambar'                                  ,
     'Fried lentil doughnut with sambar. Can be made without onion or garlic — ask when ordering.',
      14500, 'mild'  , FALSE,  12,   50),
    ('itm_gw_plain_dosa'                            , 'cat_gw_south'        , 'Plain Dosa'                                        ,
     'Crisp rice-and-lentil crepe.',
      15900, 'mild'  , FALSE,  15,   60),
    ('itm_gw_onion_dosa_plain'                      , 'cat_gw_south'        , 'Onion Dosa (Plain)'                                ,
     'Dosa griddled with onion.',
      16900, 'mild'  , FALSE,  15,   70),
    ('itm_gw_mysore_dosa_plain'                     , 'cat_gw_south'        , 'Mysore Dosa (Plain)'                               ,
     'Spread with a red chilli-garlic chutney.',
      17900, 'hot'   , FALSE,  15,   80),
    ('itm_gw_paper_dosa_plain'                      , 'cat_gw_south'        , 'Paper Dosa (Plain)'                                ,
     'Thin and extra crisp. Can be made without onion or garlic — ask when ordering.',
      17900, 'mild'  , FALSE,  15,   90),
    ('itm_gw_masala_dosa'                           , 'cat_gw_south'        , 'Masala Dosa'                                       ,
     'Filled with spiced potato. Can be made without onion or garlic — ask when ordering.',
      18900, 'medium', TRUE ,  15,  100),
    ('itm_gw_rawa_dosa_plain'                       , 'cat_gw_south'        , 'Rawa Dosa (Plain)'                                 ,
     'Semolina batter, lacy and crisp. Can be made without onion or garlic — ask when ordering.',
      18900, 'mild'  , FALSE,  15,  110),
    ('itm_gw_onion_dosa_masala'                     , 'cat_gw_south'        , 'Onion Dosa (Masala)'                               ,
     'Onion dosa with a spiced potato filling.',
      19900, 'medium', FALSE,  15,  120),
    ('itm_gw_mysore_dosa_masala'                    , 'cat_gw_south'        , 'Mysore Dosa (Masala)'                              ,
     'Chilli-garlic chutney with a potato filling.',
      19900, 'hot'   , FALSE,  15,  130),
    ('itm_gw_paper_dosa_masala'                     , 'cat_gw_south'        , 'Paper Dosa (Masala)'                               ,
     'Thin, crisp, filled with spiced potato. Can be made without onion or garlic — ask when ordering.',
      19900, 'medium', FALSE,  15,  140),
    ('itm_gw_butter_dosa_plain'                     , 'cat_gw_south'        , 'Butter Dosa (Plain)'                               ,
     'Griddled in butter. Can be made without onion or garlic — ask when ordering.',
      20900, 'mild'  , FALSE,  15,  150),
    ('itm_gw_coconut_rawa_dosa_plain'               , 'cat_gw_south'        , 'Coconut Rawa Dosa (Plain)'                         ,
     'Semolina batter with fresh coconut. Can be made without onion or garlic — ask when ordering.',
      20900, 'mild'  , FALSE,  15,  160),
    ('itm_gw_coconut_uttapam'                       , 'cat_gw_south'        , 'Coconut Uttapam'                                   ,
     'Thick pancake with fresh coconut. Can be made without onion or garlic — ask when ordering.',
      20900, 'mild'  , FALSE,  15,  170),
    ('itm_gw_onion_rawa_dosa_plain'                 , 'cat_gw_south'        , 'Onion Rawa Dosa (Plain)'                           ,
     'Semolina dosa griddled with onion.',
      20900, 'mild'  , FALSE,  15,  180),
    ('itm_gw_rawa_dosa_masala'                      , 'cat_gw_south'        , 'Rawa Dosa (Masala)'                                ,
     'Semolina dosa with a spiced potato filling. Can be made without onion or garlic — ask when ordering.',
      20900, 'medium', FALSE,  15,  190),
    ('itm_gw_uttapam_mix_onion_tomato'              , 'cat_gw_south'        , 'Uttapam (Mix / Onion / Tomato)'                    ,
     'Thick savoury pancake with your choice of topping.',
      20900, 'mild'  , FALSE,  15,  200),
    ('itm_gw_butter_dosa_masala'                    , 'cat_gw_south'        , 'Butter Dosa (Masala)'                              ,
     'Butter-griddled, with a potato filling. Can be made without onion or garlic — ask when ordering.',
      21900, 'medium', FALSE,  15,  210),
    ('itm_gw_coconut_rawa_dosa_masala'              , 'cat_gw_south'        , 'Coconut Rawa Dosa (Masala)'                        ,
     'Coconut rawa dosa, filled. Can be made without onion or garlic — ask when ordering.',
      21900, 'medium', FALSE,  15,  220),
    ('itm_gw_onion_rawa_dosa_masala'                , 'cat_gw_south'        , 'Onion Rawa Dosa (Masala)'                          ,
     'Onion rawa dosa with a potato filling.',
      21900, 'medium', FALSE,  15,  230),
    ('itm_gw_paneer_dosa'                           , 'cat_gw_south'        , 'Paneer Dosa'                                       ,
     'Filled with spiced cottage cheese. Can be made without onion or garlic — ask when ordering.',
      23900, 'medium', FALSE,  18,  240),
    ('itm_gw_paneer_uttapam'                        , 'cat_gw_south'        , 'Paneer Uttapam'                                    ,
     'Thick pancake topped with paneer. Can be made without onion or garlic — ask when ordering.',
      23900, 'mild'  , FALSE,  18,  250),

    -- Soups
    ('itm_gw_veg_clear_soup'                        , 'cat_gw_soups'        , 'Veg Clear Soup'                                    ,
     'A light, clear vegetable broth.',
       8900, 'mild'  , FALSE,  12,   10),
    ('itm_gw_hot_sour_soup'                         , 'cat_gw_soups'        , 'Hot & Sour Soup'                                   ,
     'Peppery and tart, thickened.',
       9900, 'hot'   , TRUE ,  12,   20),
    ('itm_gw_manchow_soup'                          , 'cat_gw_soups'        , 'Manchow Soup'                                      ,
     'Spiced and topped with fried noodles.',
       9900, 'hot'   , FALSE,  12,   30),
    ('itm_gw_sweet_corn_soup'                       , 'cat_gw_soups'        , 'Sweet Corn Soup'                                   ,
     'Thick, mild and sweet.',
       9900, 'mild'  , FALSE,  12,   40),
    ('itm_gw_tomato_dhaniya_soup'                   , 'cat_gw_soups'        , 'Tomato Dhaniya Soup'                               ,
     'Tomato finished with fresh coriander.',
       9900, 'mild'  , FALSE,  12,   50),
    ('itm_gw_tomato_soup'                           , 'cat_gw_soups'        , 'Tomato Soup'                                       ,
     'Classic, served with croutons.',
       9900, 'mild'  , FALSE,  12,   60),
    ('itm_gw_cream_of_mushroom_soup'                , 'cat_gw_soups'        , 'Cream Of Mushroom Soup'                            ,
     'Mushroom, blended and creamed.',
      10900, 'mild'  , FALSE,  12,   70),
    ('itm_gw_veg_talumein_soup'                     , 'cat_gw_soups'        , 'Veg Talumein Soup'                                 ,
     'Clear soup with noodles and vegetables.',
      10900, 'mild'  , FALSE,  12,   80),

    -- Grilled Specialities
    ('itm_gw_soya_chaap_roll'                       , 'cat_gw_grilled'      , 'Soya Chaap Roll'                                   ,
     'Soya chaap rolled into a paratha. From the tandoor; may be unavailable 4–6 pm.',
      14900, 'medium', FALSE,  18,   10),
    ('itm_gw_paneer_roll'                           , 'cat_gw_grilled'      , 'Paneer Roll'                                       ,
     'Cottage cheese rolled into a paratha. From the tandoor; may be unavailable 4–6 pm.',
      15900, 'medium', FALSE,  18,   20),
    ('itm_gw_hara_bhara_kebab'                      , 'cat_gw_grilled'      , 'Hara Bhara Kebab'                                  ,
     'Spinach, peas and potato, griddled.',
      26900, 'mild'  , FALSE,  20,   30),
    ('itm_gw_dahi_kebab'                            , 'cat_gw_grilled'      , 'Dahi Kebab'                                        ,
     'Hung curd kebab, soft inside. Can be made without onion or garlic — ask when ordering.',
      26900, 'mild'  , TRUE ,  20,   40),
    ('itm_gw_cheese_palak_kebab'                    , 'cat_gw_grilled'      , 'Cheese Palak Kebab'                                ,
     'Spinach and cheese, griddled.',
      28900, 'mild'  , FALSE,  20,   50),
    ('itm_gw_hariyali_pudina_chaap'                 , 'cat_gw_grilled'      , 'Hariyali Pudina Chaap'                             ,
     'Mint and coriander marinade. From the tandoor; may be unavailable 4–6 pm.',
      29900, 'medium', FALSE,  22,   60),
    ('itm_gw_dahi_ke_sholey'                        , 'cat_gw_grilled'      , 'Dahi Ke Sholey'                                    ,
     'Curd-filled parcels, fried crisp. Can be made without onion or garlic — ask when ordering.',
      29900, 'mild'  , FALSE,  20,   70),
    ('itm_gw_garlic_chaap'                          , 'cat_gw_grilled'      , 'Garlic Chaap'                                      ,
     'Heavy on the garlic. From the tandoor; may be unavailable 4–6 pm.',
      29900, 'medium', FALSE,  22,   80),
    ('itm_gw_tandoori_masala_chaap'                 , 'cat_gw_grilled'      , 'Tandoori Masala Chaap'                             ,
     'The classic red masala marinade. From the tandoor; may be unavailable 4–6 pm.',
      29900, 'medium', TRUE ,  22,   90),
    ('itm_gw_seekh_kebab'                           , 'cat_gw_grilled'      , 'Seekh Kebab'                                       ,
     'Minced vegetable seekh on the skewer. From the tandoor; may be unavailable 4–6 pm.',
      29900, 'medium', FALSE,  22,  100),
    ('itm_gw_beetroot_kebab'                        , 'cat_gw_grilled'      , 'Beetroot Kebab'                                    ,
     'Beetroot and potato, griddled.',
      30900, 'mild'  , FALSE,  20,  110),
    ('itm_gw_sweet_corn_kebab'                      , 'cat_gw_grilled'      , 'Sweet Corn Kebab'                                  ,
     'Sweet corn and potato, griddled.',
      30900, 'mild'  , FALSE,  20,  120),
    ('itm_gw_tandoori_malai_chaap'                  , 'cat_gw_grilled'      , 'Tandoori Malai Chaap'                              ,
     'Cream and cheese marinade, mild. From the tandoor; may be unavailable 4–6 pm.',
      30900, 'mild'  , TRUE ,  22,  130),
    ('itm_gw_paneer_tikka'                          , 'cat_gw_grilled'      , 'Paneer Tikka'                                      ,
     'Cottage cheese marinated in yoghurt and spices. From the tandoor; may be unavailable 4–6 pm.',
      33900, 'medium', TRUE ,  22,  140),
    ('itm_gw_kurkuri_mushroom'                      , 'cat_gw_grilled'      , 'Kurkuri Mushroom'                                  ,
     'Mushrooms in a crisp coating.',
      34900, 'medium', FALSE,  20,  150),
    ('itm_gw_kurkuri_paneer_tikka'                  , 'cat_gw_grilled'      , 'Kurkuri Paneer Tikka'                              ,
     'Paneer tikka with a crisp crust.',
      34900, 'medium', FALSE,  22,  160),
    ('itm_gw_paneer_malai_tikka'                    , 'cat_gw_grilled'      , 'Paneer Malai Tikka'                                ,
     'Cream, cheese and cardamom marinade. From the tandoor; may be unavailable 4–6 pm.',
      34900, 'mild'  , FALSE,  22,  170),

    -- Chinese Shinese
    ('itm_gw_momos_steamed'                         , 'cat_gw_chinese'      , 'Momos — Steamed'                                   ,
     'Vegetable dumplings, steamed, with chutney.',
      12900, 'mild'  , TRUE ,  15,   10),
    ('itm_gw_momos_fried'                           , 'cat_gw_chinese'      , 'Momos — Fried'                                     ,
     'The same dumplings, deep-fried.',
      14900, 'medium', FALSE,  15,   20),
    ('itm_gw_momos_tandoori'                        , 'cat_gw_chinese'      , 'Momos — Tandoori'                                  ,
     'Momos finished in the tandoor. From the tandoor; may be unavailable 4–6 pm.',
      17900, 'medium', FALSE,  18,   30),
    ('itm_gw_chilli_idli'                           , 'cat_gw_chinese'      , 'Chilli Idli'                                       ,
     'Idli tossed Indo-Chinese, with peppers.',
      15900, 'hot'   , FALSE,  15,   40),
    ('itm_gw_chilli_potato'                         , 'cat_gw_chinese'      , 'Chilli Potato'                                     ,
     'Crisp potato in a sweet-hot sauce.',
      16900, 'hot'   , TRUE ,  15,   50),
    ('itm_gw_veg_spring_roll'                       , 'cat_gw_chinese'      , 'Veg Spring Roll'                                   ,
     'Shredded vegetables in a crisp roll.',
      17900, 'mild'  , FALSE,  15,   60),
    ('itm_gw_veg_in_hot_garlic_sauce'               , 'cat_gw_chinese'      , 'Veg In Hot Garlic Sauce'                           ,
     'Vegetables in a garlic-forward sauce.',
      18900, 'hot'   , FALSE,  15,   70),
    ('itm_gw_honey_chilli_potato'                   , 'cat_gw_chinese'      , 'Honey Chilli Potato'                               ,
     'Crisp potato, honey and chilli.',
      19900, 'medium', TRUE ,  15,   80),
    ('itm_gw_veg_fried_rice'                        , 'cat_gw_chinese'      , 'Veg Fried Rice'                                    ,
     'Tossed with vegetables on a high flame.',
      19900, 'mild'  , FALSE,  15,   90),
    ('itm_gw_butter_pepper_garlic_rice'             , 'cat_gw_chinese'      , 'Butter Pepper Garlic Rice'                         ,
     'Butter, crushed pepper and garlic.',
      20900, 'medium', FALSE,  15,  100),
    ('itm_gw_chilli_gobhi'                          , 'cat_gw_chinese'      , 'Chilli Gobhi'                                      ,
     'Cauliflower in a sweet-hot sauce.',
      20900, 'hot'   , FALSE,  15,  110),
    ('itm_gw_garlic_singapuri_noodles'              , 'cat_gw_chinese'      , 'Garlic / Singapuri Noodles'                        ,
     'Your choice — garlic, or Singapuri with curry.',
      20900, 'medium', FALSE,  15,  120),
    ('itm_gw_singapuri_rice'                        , 'cat_gw_chinese'      , 'Singapuri Rice'                                    ,
     'Rice tossed with curry powder and vegetables.',
      20900, 'medium', FALSE,  15,  130),
    ('itm_gw_veg_noodles'                           , 'cat_gw_chinese'      , 'Veg Noodles'                                       ,
     'Hakka noodles with shredded vegetables.',
      20900, 'mild'  , FALSE,  15,  140),
    ('itm_gw_butter_pepper_garlic_noodles'          , 'cat_gw_chinese'      , 'Butter Pepper Garlic Noodles'                      ,
     'Noodles in butter, pepper and garlic.',
      21900, 'medium', FALSE,  15,  150),
    ('itm_gw_chilli_bell_pepper_corn'               , 'cat_gw_chinese'      , 'Chilli Bell Pepper Corn'                           ,
     'Corn and peppers, tossed.',
      22900, 'medium', FALSE,  15,  160),
    ('itm_gw_chilli_mushroom'                       , 'cat_gw_chinese'      , 'Chilli Mushroom'                                   ,
     'Mushroom in a sweet-hot sauce.',
      22900, 'hot'   , FALSE,  15,  170),
    ('itm_gw_manchurian_dry'                        , 'cat_gw_chinese'      , 'Manchurian — Dry'                                  ,
     'Vegetable balls tossed in a thick sauce.',
      22900, 'medium', FALSE,  18,  180),
    ('itm_gw_manchurian_gravy'                      , 'cat_gw_chinese'      , 'Manchurian — Gravy'                                ,
     'Vegetable balls in a pouring sauce.',
      22900, 'medium', TRUE ,  18,  190),
    ('itm_gw_veg_chopsuey'                          , 'cat_gw_chinese'      , 'Veg Chopsuey'                                      ,
     'Crisp noodles under sweet-and-sour vegetables.',
      22900, 'mild'  , FALSE,  18,  200),
    ('itm_gw_chilli_paneer_dry'                     , 'cat_gw_chinese'      , 'Chilli Paneer — Dry'                               ,
     'Paneer tossed with peppers and onion.',
      24900, 'hot'   , TRUE ,  18,  210),
    ('itm_gw_chilli_paneer_gravy'                   , 'cat_gw_chinese'      , 'Chilli Paneer — Gravy'                             ,
     'Paneer in a sweet-hot pouring sauce.',
      24900, 'hot'   , FALSE,  18,  220),
    ('itm_gw_paneer_65'                             , 'cat_gw_chinese'      , 'Paneer 65'                                         ,
     'Battered paneer, curry leaf and chilli.',
      24900, 'hot'   , FALSE,  18,  230),

    -- Separate Menu (À la Carte)
    ('itm_gw_aloo_sabji'                            , 'cat_gw_alacarte'     , 'Aloo Sabji'                                        ,
     'A thin, everyday potato curry. Can be made without onion or garlic — ask when ordering.',
      15900, 'medium', FALSE,  15,   10),
    ('itm_gw_paneer_bhurji_300_ml'                  , 'cat_gw_alacarte'     , 'Paneer Bhurji (300 ml)'                            ,
     'Crumbled paneer with onion and tomato.',
      21900, 'medium', FALSE,  18,   20),
    ('itm_gw_chole'                                 , 'cat_gw_alacarte'     , 'Chole'                                             ,
     'Chickpeas, slow-cooked and spiced dark.',
      22900, 'medium', TRUE ,  18,   30),
    ('itm_gw_chana_masala'                          , 'cat_gw_alacarte'     , 'Chana Masala'                                      ,
     'Chickpeas in an onion-tomato masala.',
      25900, 'medium', FALSE,  18,   40),
    ('itm_gw_dal_tadka'                             , 'cat_gw_alacarte'     , 'Dal Tadka'                                         ,
     'Yellow dal with a cumin and chilli tempering. Can be made without onion or garlic — ask when ordering.',
      25900, 'medium', TRUE ,  15,   50),
    ('itm_gw_jeera_aloo'                            , 'cat_gw_alacarte'     , 'Jeera Aloo'                                        ,
     'Potato tossed with cumin.',
      25900, 'mild'  , FALSE,  15,   60),
    ('itm_gw_mix_vegetable'                         , 'cat_gw_alacarte'     , 'Mix Vegetable'                                     ,
     'Seasonal vegetables in a light gravy.',
      26900, 'medium', FALSE,  18,   70),
    ('itm_gw_rajma_masala'                          , 'cat_gw_alacarte'     , 'Rajma Masala'                                      ,
     'Kidney beans, slow-cooked. Can be made without onion or garlic — ask when ordering.',
      26900, 'medium', TRUE ,  20,   80),
    ('itm_gw_aloo_gobhi_adraki'                     , 'cat_gw_alacarte'     , 'Aloo Gobhi Adraki'                                 ,
     'Potato and cauliflower with ginger. Can be made without onion or garlic — ask when ordering.',
      27900, 'medium', FALSE,  18,   90),
    ('itm_gw_dal_handi'                             , 'cat_gw_alacarte'     , 'Dal Handi'                                         ,
     'Mixed dal finished in a sealed handi.',
      27900, 'medium', FALSE,  20,  100),
    ('itm_gw_kashmiri_dum_aloo'                     , 'cat_gw_alacarte'     , 'Kashmiri Dum Aloo'                                 ,
     'Baby potatoes in a Kashmiri chilli gravy. Can be made without onion or garlic — ask when ordering.',
      27900, 'hot'   , FALSE,  20,  110),
    ('itm_gw_saag_seasonal'                         , 'cat_gw_alacarte'     , 'Saag (Seasonal)'                                   ,
     'Slow-cooked greens. Winter only.',
      27900, 'medium', FALSE,  20,  120),
    ('itm_gw_veg_handi'                             , 'cat_gw_alacarte'     , 'Veg Handi'                                         ,
     'Mixed vegetables cooked in a sealed handi.',
      27900, 'medium', FALSE,  20,  130),
    ('itm_gw_hyderabadi_chaap'                      , 'cat_gw_alacarte'     , 'Hyderabadi Chaap'                                  ,
     'Soya chaap in a Hyderabadi gravy.',
      28900, 'hot'   , FALSE,  20,  140),
    ('itm_gw_dal_makhani'                           , 'cat_gw_alacarte'     , 'Dal Makhani'                                       ,
     'Black lentils, slow-cooked overnight with butter.',
      29900, 'mild'  , TRUE ,  18,  150),
    ('itm_gw_palak_corn_masala'                     , 'cat_gw_alacarte'     , 'Palak Corn Masala'                                 ,
     'Spinach gravy with sweet corn.',
      29900, 'mild'  , FALSE,  18,  160),
    ('itm_gw_matar_paneer'                          , 'cat_gw_alacarte'     , 'Matar Paneer'                                      ,
     'Paneer and green peas in onion-tomato gravy. Can be made without onion or garlic — ask when ordering.',
      30900, 'mild'  , FALSE,  18,  170),
    ('itm_gw_shahi_paneer'                          , 'cat_gw_alacarte'     , 'Shahi Paneer'                                      ,
     'Cashew and cream gravy, mildly sweet. Can be made without onion or garlic — ask when ordering.',
      30900, 'mild'  , TRUE ,  18,  180),
    ('itm_gw_karahi_chaap'                          , 'cat_gw_alacarte'     , 'Karahi Chaap'                                      ,
     'Soya chaap with peppers and kadhai masala.',
      31900, 'medium', FALSE,  20,  190),
    ('itm_gw_paneer_corn_masala'                    , 'cat_gw_alacarte'     , 'Paneer Corn Masala'                                ,
     'Paneer and corn in a creamy masala.',
      32900, 'mild'  , FALSE,  18,  200),
    ('itm_gw_karahi_paneer'                         , 'cat_gw_alacarte'     , 'Karahi Paneer'                                     ,
     'Capsicum, tomato and freshly ground kadhai masala.',
      33900, 'medium', FALSE,  18,  210),
    ('itm_gw_lahori_paneer'                         , 'cat_gw_alacarte'     , 'Lahori Paneer'                                     ,
     'Paneer in a tangy Lahori-style gravy.',
      33900, 'medium', FALSE,  18,  220),
    ('itm_gw_malai_kofta'                           , 'cat_gw_alacarte'     , 'Malai Kofta'                                       ,
     'Paneer and potato dumplings in a cashew gravy. Can be made without onion or garlic — ask when ordering.',
      33900, 'mild'  , TRUE ,  22,  230),
    ('itm_gw_matar_mushroom'                        , 'cat_gw_alacarte'     , 'Matar Mushroom'                                    ,
     'Mushroom and green peas in a light gravy.',
      33900, 'medium', FALSE,  18,  240),
    ('itm_gw_mushroom_masala'                       , 'cat_gw_alacarte'     , 'Mushroom Masala'                                   ,
     'Mushroom in an onion-tomato masala.',
      33900, 'medium', FALSE,  18,  250),
    ('itm_gw_paneer_adraki'                         , 'cat_gw_alacarte'     , 'Paneer Adraki'                                     ,
     'Paneer with a ginger-forward gravy. Can be made without onion or garlic — ask when ordering.',
      35900, 'medium', FALSE,  18,  260),
    ('itm_gw_paneer_butter_masala'                  , 'cat_gw_alacarte'     , 'Paneer Butter Masala'                              ,
     'Tomato, butter and kasuri methi. Can be made without onion or garlic — ask when ordering.',
      35900, 'mild'  , TRUE ,  18,  270),
    ('itm_gw_paneer_lababdar'                       , 'cat_gw_alacarte'     , 'Paneer Lababdar'                                   ,
     'Tomato and cashew, finished with butter and cream. Can be made without onion or garlic — ask when ordering.',
      35900, 'mild'  , TRUE ,  20,  280),
    ('itm_gw_paneer_pasanda'                        , 'cat_gw_alacarte'     , 'Paneer Pasanda'                                    ,
     'Stuffed paneer slices in a rich gravy. Can be made without onion or garlic — ask when ordering.',
      35900, 'mild'  , FALSE,  22,  290),
    ('itm_gw_paneer_tikka_masala'                   , 'cat_gw_alacarte'     , 'Paneer Tikka Masala'                               ,
     'Tandoori paneer folded into a spiced gravy.',
      35900, 'medium', TRUE ,  20,  300),
    ('itm_gw_paneer_do_pyaza'                       , 'cat_gw_alacarte'     , 'Paneer Do Pyaza'                                   ,
     'Onion twice over — in the base and seared through.',
      35900, 'medium', FALSE,  18,  310),

    -- Rice & Raita
    ('itm_gw_boondi_raita'                          , 'cat_gw_rice'         , 'Boondi Raita'                                      ,
     'Gram-flour pearls in whisked curd.',
      11900, 'mild'  , FALSE,   8,   10),
    ('itm_gw_pudina_raita'                          , 'cat_gw_rice'         , 'Pudina Raita'                                      ,
     'Curd with fresh mint.',
      12900, 'mild'  , FALSE,   8,   20),
    ('itm_gw_cucumber_raita'                        , 'cat_gw_rice'         , 'Cucumber Raita'                                    ,
     'Curd with grated cucumber.',
      12900, 'mild'  , FALSE,   8,   30),
    ('itm_gw_mix_vegetable_raita'                   , 'cat_gw_rice'         , 'Mix Vegetable Raita'                               ,
     'Curd with chopped vegetables.',
      12900, 'mild'  , FALSE,   8,   40),
    ('itm_gw_pineapple_raita'                       , 'cat_gw_rice'         , 'Pineapple Raita'                                   ,
     'Sweet curd with pineapple.',
      14900, 'mild'  , FALSE,   8,   50),
    ('itm_gw_steamed_rice'                          , 'cat_gw_rice'         , 'Steamed Rice'                                      ,
     'Plain basmati.',
      15900, NULL    , FALSE,  15,   60),
    ('itm_gw_jeera_rice'                            , 'cat_gw_rice'         , 'Jeera Rice'                                        ,
     'Basmati tempered with cumin.',
      17900, 'mild'  , TRUE ,  15,   70),
    ('itm_gw_matar_pulao'                           , 'cat_gw_rice'         , 'Matar Pulao'                                       ,
     'Rice cooked with green peas.',
      18900, 'mild'  , FALSE,  18,   80),
    ('itm_gw_veg_pulao'                             , 'cat_gw_rice'         , 'Veg Pulao'                                         ,
     'Basmati with seasonal vegetables and whole spices.',
      19900, 'mild'  , FALSE,  18,   90),
    ('itm_gw_navratan_pulao'                        , 'cat_gw_rice'         , 'Navratan Pulao'                                    ,
     'Rice with nine vegetables, fruit and nuts.',
      20900, 'mild'  , FALSE,  20,  100),
    ('itm_gw_veg_biryani_with_gravy_burani_raita'   , 'cat_gw_rice'         , 'Veg Biryani With Gravy & Burani Raita'             ,
     'Dum-cooked biryani, served with gravy and garlic raita.',
      26900, 'medium', TRUE ,  25,  110),
    ('itm_gw_veg_chaap_biryani_with_gravy_burani_ra', 'cat_gw_rice'         , 'Veg Chaap Biryani With Gravy & Burani Raita'       ,
     'Soya chaap biryani with gravy and garlic raita.',
      27900, 'medium', FALSE,  25,  120),

    -- Rice / Noodles Meals
    ('itm_gw_chole_with_2_roti'                     , 'cat_gw_meals'        , 'Chole With 2 Roti'                                 ,
     'Chickpea curry with two rotis.',
      19900, 'medium', FALSE,  18,   10),
    ('itm_gw_chole_with_rice'                       , 'cat_gw_meals'        , 'Chole With Rice'                                   ,
     'Chickpea curry with steamed rice.',
      19900, 'medium', FALSE,  18,   20),
    ('itm_gw_dal_makhani_with_2_roti'               , 'cat_gw_meals'        , 'Dal Makhani With 2 Roti'                           ,
     'Black lentils with two rotis.',
      19900, 'mild'  , TRUE ,  18,   30),
    ('itm_gw_dal_makhani_with_rice'                 , 'cat_gw_meals'        , 'Dal Makhani With Rice'                             ,
     'Black lentils with steamed rice.',
      19900, 'mild'  , FALSE,  18,   40),
    ('itm_gw_dal_tadka_with_2_roti'                 , 'cat_gw_meals'        , 'Dal Tadka With 2 Roti'                             ,
     'Tempered yellow dal with two rotis.',
      19900, 'medium', FALSE,  18,   50),
    ('itm_gw_dal_tadka_with_rice'                   , 'cat_gw_meals'        , 'Dal Tadka With Rice'                               ,
     'Tempered yellow dal with steamed rice.',
      19900, 'medium', FALSE,  18,   60),
    ('itm_gw_manchurian_with_noodles'               , 'cat_gw_meals'        , 'Manchurian With Noodles'                           ,
     'Manchurian gravy over hakka noodles.',
      19900, 'medium', FALSE,  18,   70),
    ('itm_gw_manchurian_with_rice'                  , 'cat_gw_meals'        , 'Manchurian With Rice'                              ,
     'Manchurian gravy over fried rice.',
      19900, 'medium', FALSE,  18,   80),
    ('itm_gw_paneer_gravy_with_2_roti'              , 'cat_gw_meals'        , 'Paneer Gravy With 2 Roti'                          ,
     'The day''s paneer with two rotis.',
      19900, 'medium', TRUE ,  18,   90),
    ('itm_gw_paneer_gravy_with_rice'                , 'cat_gw_meals'        , 'Paneer Gravy With Rice'                            ,
     'The day''s paneer with steamed rice.',
      19900, 'medium', FALSE,  18,  100),
    ('itm_gw_rajma_with_2_roti'                     , 'cat_gw_meals'        , 'Rajma With 2 Roti'                                 ,
     'Kidney beans with two rotis.',
      19900, 'medium', FALSE,  18,  110),
    ('itm_gw_rajma_with_rice'                       , 'cat_gw_meals'        , 'Rajma With Rice'                                   ,
     'Kidney beans with steamed rice.',
      19900, 'medium', FALSE,  18,  120),
    ('itm_gw_chilli_paneer_gravy_with_noodles'      , 'cat_gw_meals'        , 'Chilli Paneer Gravy With Noodles'                  ,
     'Chilli paneer over hakka noodles.',
      20900, 'hot'   , FALSE,  18,  130),
    ('itm_gw_chilli_paneer_gravy_with_rice'         , 'cat_gw_meals'        , 'Chilli Paneer Gravy With Rice'                     ,
     'Chilli paneer over fried rice.',
      20900, 'hot'   , FALSE,  18,  140),

    -- Breads
    ('itm_gw_papad'                                 , 'cat_gw_breads'       , 'Papad'                                             ,
     'Roasted or fried.',
       1500, 'mild'  , FALSE,   5,   10),
    ('itm_gw_atta_puri_1_pc'                        , 'cat_gw_breads'       , 'Atta Puri (1 pc)'                                  ,
     'Whole-wheat puri.',
       2000, NULL    , FALSE,   8,   20),
    ('itm_gw_bedmi_puri_1_pc'                       , 'cat_gw_breads'       , 'Bedmi Puri (1 pc)'                                 ,
     'Puri stuffed with spiced urad dal.',
       2500, 'medium', FALSE,  10,   30),
    ('itm_gw_tandoori_plain_roti'                   , 'cat_gw_breads'       , 'Tandoori Plain Roti'                               ,
     'Whole wheat. From the tandoor; may be unavailable 4–6 pm.',
       2900, NULL    , FALSE,   8,   40),
    ('itm_gw_tandoori_butter_roti'                  , 'cat_gw_breads'       , 'Tandoori Butter Roti'                              ,
     'Brushed with butter. From the tandoor; may be unavailable 4–6 pm.',
       3900, NULL    , TRUE ,   8,   50),
    ('itm_gw_garlic_roti'                           , 'cat_gw_breads'       , 'Garlic Roti'                                       ,
     'Fresh garlic and coriander. From the tandoor; may be unavailable 4–6 pm.',
       5900, 'mild'  , FALSE,   8,   60),
    ('itm_gw_green_salad'                           , 'cat_gw_breads'       , 'Green Salad'                                       ,
     'Onion, cucumber, tomato and lemon.',
       6900, NULL    , FALSE,   5,   70),
    ('itm_gw_plain_naan'                            , 'cat_gw_breads'       , 'Plain Naan'                                        ,
     'Refined flour, from the tandoor. From the tandoor; may be unavailable 4–6 pm.',
       6900, NULL    , FALSE,   8,   80),
    ('itm_gw_butter_naan'                           , 'cat_gw_breads'       , 'Butter Naan'                                       ,
     'Brushed with butter. From the tandoor; may be unavailable 4–6 pm.',
       7900, NULL    , TRUE ,   8,   90),
    ('itm_gw_lachha_paratha'                        , 'cat_gw_breads'       , 'Lachha Paratha'                                    ,
     'Layered and flaky.',
       7900, NULL    , FALSE,  10,  100),
    ('itm_gw_corn_masala_papad'                     , 'cat_gw_breads'       , 'Corn Masala Papad'                                 ,
     'Papad topped with spiced corn.',
       8900, 'medium', FALSE,   8,  110),
    ('itm_gw_garlic_naan'                           , 'cat_gw_breads'       , 'Garlic Naan'                                       ,
     'Fresh garlic and coriander. From the tandoor; may be unavailable 4–6 pm.',
       8900, 'mild'  , TRUE ,   8,  120),
    ('itm_gw_makke_ki_roti'                         , 'cat_gw_breads'       , 'Makke Ki Roti'                                     ,
     'Maize flour, griddled. Best with saag.',
       8900, NULL    , FALSE,  10,  130),
    ('itm_gw_missi_roti'                            , 'cat_gw_breads'       , 'Missi Roti'                                        ,
     'Gram flour and spices in the dough.',
       8900, 'medium', FALSE,  10,  140),
    ('itm_gw_pudina_paratha'                        , 'cat_gw_breads'       , 'Pudina Paratha'                                    ,
     'Layered paratha with mint.',
       8900, 'mild'  , FALSE,  10,  150),
    ('itm_gw_amritsari_aloo_kulcha'                 , 'cat_gw_breads'       , 'Amritsari Aloo Kulcha'                             ,
     'Stuffed with spiced potato, Amritsar style.',
      10900, 'medium', TRUE ,  12,  160),
    ('itm_gw_amritsari_onion_kulcha'                , 'cat_gw_breads'       , 'Amritsari Onion Kulcha'                            ,
     'Stuffed with spiced onion.',
      10900, 'medium', FALSE,  12,  170),
    ('itm_gw_amritsari_mix_kulcha'                  , 'cat_gw_breads'       , 'Amritsari Mix Kulcha'                              ,
     'Potato, onion and paneer stuffing.',
      11900, 'medium', FALSE,  12,  180),
    ('itm_gw_amritsari_paneer_kulcha'               , 'cat_gw_breads'       , 'Amritsari Paneer Kulcha'                           ,
     'Stuffed with spiced cottage cheese.',
      12900, 'medium', FALSE,  12,  190),
    ('itm_gw_chur_chur_naan'                        , 'cat_gw_breads'       , 'Chur Chur Naan'                                    ,
     'Crushed at the tandoor, buttered heavily.',
      14900, 'mild'  , TRUE ,  12,  200),

    -- Set Menu (Thalis)
    ('itm_gw_executive_thali'                       , 'cat_gw_thali'        , 'Executive Thali'                                   ,
     'Dal makhani, veg of the day, 2 butter roti, rice, raita and salad.',
      26900, 'medium', TRUE ,  25,   10),
    ('itm_gw_ganeshwaram_special_thali'             , 'cat_gw_thali'        , 'Ganeshwaram Special Thali'                         ,
     'Dal makhani, paneer and veg of the day, 1 butter roti, 1 butter naan, raita, rice, salad, pickle and sweet.',
      32900, 'medium', TRUE ,  25,   20),
    ('itm_gw_ganeshwaram_seasonal_thali'            , 'cat_gw_thali'        , 'Ganeshwaram Seasonal Thali'                        ,
     'Saag, dal tadka, aloo gobhi, paneer of the day, 2 makke ki roti, chaach or lassi, salad, papad, pickle, gur and sweet.',
      33900, 'medium', FALSE,  25,   30),
    ('itm_gw_ganeshwaram_deluxe_thali'              , 'cat_gw_thali'        , 'Ganeshwaram Deluxe Thali'                          ,
     'Dal makhani, paneer of the day, chole, mix vegetable, 1 butter naan, 1 laccha paratha, rice, raita, salad, papad, pickle and sweet.',
      35900, 'medium', TRUE ,  28,   40),

    -- Platters
    ('itm_gw_amritsari_kulcha_platter'              , 'cat_gw_platters'     , 'Amritsari Kulcha Platter'                          ,
     '2 stuffed Amritsari kulcha, dal makhani, raita and chutney.',
      26900, 'medium', FALSE,  25,   10),
    ('itm_gw_chaat_platter_with_dahi_puri'          , 'cat_gw_platters'     , 'Chaat Platter With Dahi Puri'                      ,
     '3 dahi puri, aloo tikki with chutney, samosa chaat, bhel puri and dahi bhalla.',
      26900, 'medium', TRUE ,  20,   20),
    ('itm_gw_chaat_platter_with_pani_puri'          , 'cat_gw_platters'     , 'Chaat Platter With Pani Puri'                      ,
     '3 pani puri, aloo tikki with chutney, samosa chaat, bhel puri and dahi bhalla.',
      26900, 'medium', FALSE,  20,   30),
    ('itm_gw_continental_platter'                   , 'cat_gw_platters'     , 'Continental Platter'                               ,
     'Mini pizza, fries with sauce, garlic bread and baked vegetables.',
      26900, 'mild'  , FALSE,  25,   40),
    ('itm_gw_chinese_platter_with_noodles'          , 'cat_gw_platters'     , 'Chinese Platter With Noodles'                      ,
     'Noodles, honey chilli potato, chilli paneer dry and manchurian gravy.',
      32900, 'medium', TRUE ,  25,   50),
    ('itm_gw_chinese_platter_with_rice'             , 'cat_gw_platters'     , 'Chinese Platter With Rice'                         ,
     'Rice, honey chilli potato, chilli paneer dry and manchurian gravy.',
      32900, 'medium', FALSE,  25,   60),
    ('itm_gw_south_indian_platter'                  , 'cat_gw_platters'     , 'South Indian Platter'                              ,
     'Uttapam, masala dosa, 1 vada, 1 idli, sambar and chutney.',
      32900, 'mild'  , FALSE,  25,   70),
    ('itm_gw_kebab_platter'                         , 'cat_gw_platters'     , 'Kebab Platter'                                     ,
     'Seekh kebab, dahi kebab, beetroot kebab and cheese palak kebab.',
      33900, 'medium', FALSE,  28,   80),
    ('itm_gw_soya_chaap_platter'                    , 'cat_gw_platters'     , 'Soya Chaap Platter'                                ,
     'Malai chaap, garlic chaap, hariyali pudina chaap and masala chaap.',
      33900, 'medium', TRUE ,  28,   90),
    ('itm_gw_tandoori_platter'                      , 'cat_gw_platters'     , 'Tandoori Platter'                                  ,
     'Paneer tikka, malai chaap, seekh kebab, stuffed potato, dal makhani and a small butter naan.',
      34900, 'medium', TRUE ,  30,  100),

    -- Sizzlers
    ('itm_gw_momos_sizzler'                         , 'cat_gw_sizzlers'     , 'Momos Sizzler'                                     ,
     'Steamed, fried and tandoori momos together.',
      27900, 'medium', FALSE,  25,   10),
    ('itm_gw_chinese_sizzler'                       , 'cat_gw_sizzlers'     , 'Chinese Sizzler'                                   ,
     'Fried rice, veg noodles and manchurian gravy.',
      31900, 'medium', FALSE,  25,   20),
    ('itm_gw_soya_chaap_sizzler'                    , 'cat_gw_sizzlers'     , 'Soya Chaap Sizzler'                                ,
     'Achari, masala and malai chaap.',
      33900, 'medium', FALSE,  25,   30),
    ('itm_gw_tandoori_sizzler'                      , 'cat_gw_sizzlers'     , 'Tandoori Sizzler'                                  ,
     'Paneer tikka, malai chaap, masala chaap and stuffed potato.',
      34900, 'medium', TRUE ,  28,   40),
    ('itm_gw_paneer_tikka_sizzler'                  , 'cat_gw_sizzlers'     , 'Paneer Tikka Sizzler'                              ,
     'Paneer tikka, paneer malai tikka and kurkuri paneer tikka.',
      36900, 'medium', FALSE,  28,   50),

    -- Pizzas, Pasta, Burgers & Salads
    ('itm_gw_cold_sandwich_with_french_fries'       , 'cat_gw_continental'  , 'Cold Sandwich With French Fries'                   ,
     'Vegetables and chutney, served cold, with fries.',
       8900, 'mild'  , FALSE,  12,   10),
    ('itm_gw_french_fries'                          , 'cat_gw_continental'  , 'French Fries'                                      ,
     'Salted, with ketchup.',
       8900, NULL    , FALSE,  10,   20),
    ('itm_gw_garlic_bread'                          , 'cat_gw_continental'  , 'Garlic Bread'                                      ,
     'Toasted with garlic butter.',
       8900, 'mild'  , FALSE,  12,   30),
    ('itm_gw_aloo_tikki_burger_with_french_fries'   , 'cat_gw_continental'  , 'Aloo Tikki Burger With French Fries'               ,
     'Potato patty burger with fries.',
       9900, 'medium', FALSE,  15,   40),
    ('itm_gw_veg_burger_with_french_fries'          , 'cat_gw_continental'  , 'Veg Burger With French Fries'                      ,
     'Vegetable patty burger with fries.',
      10900, 'mild'  , FALSE,  15,   50),
    ('itm_gw_veg_cheese_grilled_sandwich_with_frenc', 'cat_gw_continental'  , 'Veg & Cheese Grilled Sandwich With French Fries'   ,
     'Grilled sandwich with fries.',
      12900, 'mild'  , FALSE,  15,   60),
    ('itm_gw_paneer_burger_with_french_fries'       , 'cat_gw_continental'  , 'Paneer Burger With French Fries'                   ,
     'Paneer patty burger with fries.',
      13900, 'medium', FALSE,  15,   70),
    ('itm_gw_aloo_chana_chaat_salad'                , 'cat_gw_continental'  , 'Aloo Chana Chaat Salad'                            ,
     'Potato and chickpea, dressed as chaat.',
      16900, 'medium', FALSE,  12,   80),
    ('itm_gw_paneer_tikka_sandwich_with_french_frie', 'cat_gw_continental'  , 'Paneer Tikka Sandwich With French Fries'           ,
     'Tandoori paneer in a sandwich, with fries.',
      16900, 'medium', TRUE ,  18,   90),
    ('itm_gw_cold_pasta_salad'                      , 'cat_gw_continental'  , 'Cold Pasta Salad'                                  ,
     'Pasta tossed cold with vegetables.',
      17900, 'mild'  , FALSE,  12,  100),
    ('itm_gw_russian_salad'                         , 'cat_gw_continental'  , 'Russian Salad'                                     ,
     'Vegetables and fruit in a creamy dressing.',
      18900, 'mild'  , FALSE,  12,  110),
    ('itm_gw_club_sandwich_with_french_fries'       , 'cat_gw_continental'  , 'Club Sandwich With French Fries'                   ,
     'Triple-decker, with fries.',
      19900, 'mild'  , FALSE,  18,  120),
    ('itm_gw_plain_cheese_pizza'                    , 'cat_gw_continental'  , 'Plain Cheese Pizza'                                ,
     'Mozzarella on a tomato base.',
      20900, 'mild'  , FALSE,  18,  130),
    ('itm_gw_corn_mushroom_pizza'                   , 'cat_gw_continental'  , 'Corn Mushroom Pizza'                               ,
     'Sweet corn and mushroom.',
      21900, 'mild'  , FALSE,  18,  140),
    ('itm_gw_pink_sauce_pasta_with_garlic_bread'    , 'cat_gw_continental'  , 'Pink Sauce Pasta With Garlic Bread'                ,
     'Tomato and cream sauce, with garlic bread.',
      21900, 'mild'  , TRUE ,  18,  150),
    ('itm_gw_tomato_pasta_with_garlic_bread'        , 'cat_gw_continental'  , 'Tomato Pasta With Garlic Bread'                    ,
     'Tomato sauce, with garlic bread.',
      21900, 'mild'  , FALSE,  18,  160),
    ('itm_gw_veg_supreme_pizza'                     , 'cat_gw_continental'  , 'Veg Supreme Pizza'                                 ,
     'Loaded with vegetables.',
      21900, 'mild'  , FALSE,  18,  170),
    ('itm_gw_cheese_pasta_with_garlic_bread'        , 'cat_gw_continental'  , 'Cheese Pasta With Garlic Bread'                    ,
     'Cheese sauce, with garlic bread.',
      22900, 'mild'  , FALSE,  18,  180),
    ('itm_gw_club_pizza'                            , 'cat_gw_continental'  , 'Club Pizza'                                        ,
     'The house pizza, fully loaded.',
      25900, 'mild'  , FALSE,  20,  190),

    -- Extra (Add On)
    ('itm_gw_pav'                                   , 'cat_gw_addon'        , 'Pav'                                               ,
     'Two buttered pav.',
       3000, NULL    , FALSE,   5,   10),
    ('itm_gw_curd'                                  , 'cat_gw_addon'        , 'Curd'                                              ,
     'A bowl of plain curd.',
       4000, NULL    , FALSE,   5,   20),
    ('itm_gw_kulcha'                                , 'cat_gw_addon'        , 'Kulcha'                                            ,
     'One plain kulcha.',
       4000, NULL    , FALSE,   8,   30),
    ('itm_gw_sambar'                                , 'cat_gw_addon'        , 'Sambar'                                            ,
     'An extra bowl of sambar.',
       5000, 'mild'  , FALSE,   5,   40),
    ('itm_gw_bhatura'                               , 'cat_gw_addon'        , 'Bhatura'                                           ,
     'One fried bhatura.',
       6000, NULL    , FALSE,   8,   50),
    ('itm_gw_matar'                                 , 'cat_gw_addon'        , 'Matar'                                             ,
     'A bowl of spiced white peas.',
       6000, 'medium', FALSE,   5,   60),
    ('itm_gw_bhaji'                                 , 'cat_gw_addon'        , 'Bhaji'                                             ,
     'An extra bowl of pav bhaji masala.',
       7000, 'medium', FALSE,   8,   70),
    ('itm_gw_boondi_raita_2'                        , 'cat_gw_addon'        , 'Boondi Raita'                                      ,
     'An extra bowl of boondi raita.',
       7000, 'mild'  , FALSE,   5,   80),
    ('itm_gw_chole_2'                               , 'cat_gw_addon'        , 'Chole'                                             ,
     'An extra bowl of chickpea curry.',
       7000, 'medium', FALSE,   5,   90),

    -- Beverages
    ('itm_gw_black_coffee_with_2_cookies'           , 'cat_gw_beverages'    , 'Black Coffee (with 2 cookies)'                     ,
     'Served with two cookies.',
       5000, NULL    , FALSE,   6,   10),
    ('itm_gw_tea_with_2_cookies'                    , 'cat_gw_beverages'    , 'Tea (with 2 cookies)'                              ,
     'Masala chai, with two cookies.',
       5000, NULL    , TRUE ,   6,   20),
    ('itm_gw_fresh_lime_water_masala'               , 'cat_gw_beverages'    , 'Fresh Lime Water — Masala'                         ,
     'Fresh lime, still water, black salt and spice.',
       5900, 'mild'  , FALSE,   5,   30),
    ('itm_gw_fresh_lime_water_salted'               , 'cat_gw_beverages'    , 'Fresh Lime Water — Salted'                         ,
     'Fresh lime and still water, salted.',
       5900, NULL    , FALSE,   5,   40),
    ('itm_gw_fresh_lime_water_sweet'                , 'cat_gw_beverages'    , 'Fresh Lime Water — Sweet'                          ,
     'Fresh lime and still water, sweetened.',
       5900, NULL    , FALSE,   5,   50),
    ('itm_gw_chaach'                                , 'cat_gw_beverages'    , 'Chaach'                                            ,
     'Spiced buttermilk, chilled.',
       7000, 'mild'  , FALSE,   5,   60),
    ('itm_gw_hot_coffee_with_2_cookies'             , 'cat_gw_beverages'    , 'Hot Coffee (with 2 cookies)'                       ,
     'Served with two cookies.',
       7000, NULL    , FALSE,   6,   70),
    ('itm_gw_sweet_lassi'                           , 'cat_gw_beverages'    , 'Sweet Lassi'                                       ,
     'Thick, churned yoghurt.',
       7500, NULL    , TRUE ,   6,   80),
    ('itm_gw_fresh_lemon_soda_masala'               , 'cat_gw_beverages'    , 'Fresh Lemon Soda — Masala'                         ,
     'Lime, soda, black salt and spice.',
       8000, 'mild'  , FALSE,   5,   90),
    ('itm_gw_fresh_lemon_soda_salted'               , 'cat_gw_beverages'    , 'Fresh Lemon Soda — Salted'                         ,
     'Lime and soda, salted.',
       8000, NULL    , FALSE,   5,  100),
    ('itm_gw_fresh_lemon_soda_sweet'                , 'cat_gw_beverages'    , 'Fresh Lemon Soda — Sweet'                          ,
     'Lime and soda, sweetened.',
       8000, NULL    , FALSE,   5,  110),
    ('itm_gw_lemon_ice_tea'                         , 'cat_gw_beverages'    , 'Lemon Ice Tea'                                     ,
     'Chilled tea with lemon.',
       8000, NULL    , FALSE,   6,  120),
    ('itm_gw_cold_coffee'                           , 'cat_gw_beverages'    , 'Cold Coffee'                                       ,
     'Blended and chilled.',
       9000, NULL    , TRUE ,   8,  130),
    ('itm_gw_cold_coffee_with_ice_cream'            , 'cat_gw_beverages'    , 'Cold Coffee With Ice Cream'                        ,
     'Cold coffee topped with a scoop.',
      11000, NULL    , FALSE,   8,  140),

    -- Shakes
    ('itm_gw_banana_shake'                          , 'cat_gw_shakes'       , 'Banana Shake'                                      ,
     'Thick banana milkshake.',
      12900, NULL    , FALSE,   8,   10),
    ('itm_gw_butter_scotch_shake'                   , 'cat_gw_shakes'       , 'Butter Scotch Shake'                               ,
     'Butterscotch, blended thick.',
      12900, NULL    , FALSE,   8,   20),
    ('itm_gw_chocolate_shake'                       , 'cat_gw_shakes'       , 'Chocolate Shake'                                   ,
     'Chocolate, blended thick.',
      12900, NULL    , TRUE ,   8,   30),
    ('itm_gw_khajur_shake'                          , 'cat_gw_shakes'       , 'Khajur Shake'                                      ,
     'Dates blended with milk.',
      12900, NULL    , FALSE,   8,   40),
    ('itm_gw_kitkat_shake_chocolate_based'          , 'cat_gw_shakes'       , 'Kitkat Shake (Chocolate Based)'                    ,
     'KitKat blended into a chocolate base.',
      12900, NULL    , FALSE,   8,   50),
    ('itm_gw_kitkat_shake_vanilla_based'            , 'cat_gw_shakes'       , 'Kitkat Shake (Vanilla Based)'                      ,
     'KitKat blended into a vanilla base.',
      12900, NULL    , FALSE,   8,   60),
    ('itm_gw_mango_shake'                           , 'cat_gw_shakes'       , 'Mango Shake'                                       ,
     'Mango, blended thick.',
      12900, NULL    , TRUE ,   8,   70),
    ('itm_gw_oreo_shake_chocolate_based'            , 'cat_gw_shakes'       , 'Oreo Shake (Chocolate Based)'                      ,
     'Oreo blended into a chocolate base.',
      12900, NULL    , FALSE,   8,   80),
    ('itm_gw_oreo_shake_vanilla_based'              , 'cat_gw_shakes'       , 'Oreo Shake (Vanilla Based)'                        ,
     'Oreo blended into a vanilla base.',
      12900, NULL    , FALSE,   8,   90),
    ('itm_gw_strawberry_shake'                      , 'cat_gw_shakes'       , 'Strawberry Shake'                                  ,
     'Strawberry, blended thick.',
      12900, NULL    , FALSE,   8,  100),
    ('itm_gw_vanilla_shake'                         , 'cat_gw_shakes'       , 'Vanilla Shake'                                     ,
     'Vanilla, blended thick.',
      12900, NULL    , FALSE,   8,  110),

    -- Mocktails
    ('itm_gw_masala_coke'                           , 'cat_gw_mocktails'    , 'Masala Coke'                                       ,
     'Cola with black salt and lime.',
       7900, 'mild'  , FALSE,   5,   10),
    ('itm_gw_blue_lagoon'                           , 'cat_gw_mocktails'    , 'Blue Lagoon'                                       ,
     'Blue curacao syrup, lime and soda.',
       9900, NULL    , FALSE,   6,   20),
    ('itm_gw_green_apple_shooter'                   , 'cat_gw_mocktails'    , 'Green Apple Shooter'                               ,
     'Green apple, lime and soda.',
       9900, NULL    , FALSE,   6,   30),
    ('itm_gw_mango_shooter'                         , 'cat_gw_mocktails'    , 'Mango Shooter'                                     ,
     'Mango, lime and soda.',
       9900, NULL    , FALSE,   6,   40),
    ('itm_gw_strawberry_shooter'                    , 'cat_gw_mocktails'    , 'Strawberry Shooter'                                ,
     'Strawberry, lime and soda.',
       9900, NULL    , FALSE,   6,   50),
    ('itm_gw_virgin_mojito'                         , 'cat_gw_mocktails'    , 'Virgin Mojito'                                     ,
     'Mint, lime and soda, muddled.',
       9900, NULL    , TRUE ,   6,   60),
    ('itm_gw_fruit_punch'                           , 'cat_gw_mocktails'    , 'Fruit Punch'                                       ,
     'Mixed fruit, chilled.',
      11900, NULL    , FALSE,   6,   70),

    -- Ice Creams
    ('itm_gw_butter_scotch_1_scoop'                 , 'cat_gw_icecream'     , 'Butter Scotch (1 scoop)'                           ,
     'One scoop.',
       6000, NULL    , FALSE,   5,   10),
    ('itm_gw_chocolate_1_scoop'                     , 'cat_gw_icecream'     , 'Chocolate (1 scoop)'                               ,
     'One scoop.',
       6000, NULL    , FALSE,   5,   20),
    ('itm_gw_kesar_pista_1_scoop'                   , 'cat_gw_icecream'     , 'Kesar Pista (1 scoop)'                             ,
     'Saffron and pistachio, one scoop.',
       6000, NULL    , FALSE,   5,   30),
    ('itm_gw_mango_1_scoop'                         , 'cat_gw_icecream'     , 'Mango (1 scoop)'                                   ,
     'One scoop.',
       6000, NULL    , FALSE,   5,   40),
    ('itm_gw_strawberry_1_scoop'                    , 'cat_gw_icecream'     , 'Strawberry (1 scoop)'                              ,
     'One scoop.',
       6000, NULL    , FALSE,   5,   50),
    ('itm_gw_vanilla_1_scoop'                       , 'cat_gw_icecream'     , 'Vanilla (1 scoop)'                                 ,
     'One scoop.',
       6000, NULL    , FALSE,   5,   60),
    ('itm_gw_ice_cream_sundae'                      , 'cat_gw_icecream'     , 'Ice Cream Sundae'                                  ,
     'Scoops with sauce, nuts and a wafer.',
      18000, NULL    , TRUE ,   8,   70),

    -- Desserts
    ('itm_gw_sponge_rasgulla_1_pc'                  , 'cat_gw_desserts'     , 'Sponge Rasgulla (1 pc)'                            ,
     'Chhena in light syrup.',
       2500, NULL    , FALSE,   5,   10),
    ('itm_gw_bengali_beruda_1_pc'                   , 'cat_gw_desserts'     , 'Bengali Beruda (1 pc)'                             ,
     'Bengali chhena sweet.',
       3500, NULL    , FALSE,   5,   20),
    ('itm_gw_dry_gulab_jamun_1_pc'                  , 'cat_gw_desserts'     , 'Dry Gulab Jamun (1 pc)'                            ,
     'Fried khoya ball, rolled without syrup.',
       3500, NULL    , FALSE,   5,   30),
    ('itm_gw_gulab_jamun_1_pc'                      , 'cat_gw_desserts'     , 'Gulab Jamun (1 pc)'                                ,
     'Warm, in sugar syrup.',
       3500, NULL    , TRUE ,   5,   40),
    ('itm_gw_rajbhog_1_pc'                          , 'cat_gw_desserts'     , 'Rajbhog (1 pc)'                                    ,
     'A large chhena ball stuffed with nuts and saffron.',
       3500, NULL    , FALSE,   5,   50),
    ('itm_gw_badam_chaap_1_pc'                      , 'cat_gw_desserts'     , 'Badam Chaap (1 pc)'                                ,
     'Almond sweet, shaped and pressed.',
       4500, NULL    , FALSE,   5,   60),
    ('itm_gw_malai_chaap_sweet_1_pc'                , 'cat_gw_desserts'     , 'Malai Chaap Sweet (1 pc)'                          ,
     'Layered malai sweet.',
       4500, NULL    , FALSE,   5,   70),
    ('itm_gw_rasmalai_1_pc'                         , 'cat_gw_desserts'     , 'Rasmalai (1 pc)'                                   ,
     'Chhena discs in thickened saffron milk.',
       4500, NULL    , TRUE ,   5,   80),
    ('itm_gw_chenna_toast_1_pc'                     , 'cat_gw_desserts'     , 'Chenna Toast (1 pc)'                               ,
     'Griddled chhena, caramelised on the outside.',
       5000, NULL    , FALSE,   5,   90),
    ('itm_gw_rabri_rasmalai_1_pc'                   , 'cat_gw_desserts'     , 'Rabri Rasmalai (1 pc)'                             ,
     'Rasmalai under a spoon of rabri.',
       5500, NULL    , FALSE,   5,  100),
    ('itm_gw_laddu_box_4_pcs'                       , 'cat_gw_desserts'     , 'Laddu Box (4 pcs)'                                 ,
     'Four laddus, boxed.',
       9500, NULL    , FALSE,   5,  110),
    ('itm_gw_motichur_laddu_4_pcs'                  , 'cat_gw_desserts'     , 'Motichur Laddu (4 pcs)'                            ,
     'Four fine-boondi laddus.',
       9500, NULL    , FALSE,   5,  120),
    ('itm_gw_mathura_peda_per_kg'                   , 'cat_gw_desserts'     , 'Mathura Peda (per kg)'                             ,
     'Roasted khoya peda, Mathura style.',
      51000, NULL    , FALSE,   5,  130),
    ('itm_gw_mathura_peda_modak_per_kg'             , 'cat_gw_desserts'     , 'Mathura Peda Modak (per kg)'                       ,
     'Mathura peda shaped as modak.',
      51000, NULL    , FALSE,   5,  140),
    ('itm_gw_ras_berry_per_kg'                      , 'cat_gw_desserts'     , 'Ras Berry (per kg)'                                ,
     'Chhena sweet, berry-shaped.',
      51000, NULL    , FALSE,   5,  150),
    ('itm_gw_bengali_beruda_per_kg'                 , 'cat_gw_desserts'     , 'Bengali Beruda (per kg)'                           ,
     'Bengali chhena sweet, by weight.',
      52000, NULL    , FALSE,   5,  160),
    ('itm_gw_balushahi_per_kg'                      , 'cat_gw_desserts'     , 'Balushahi (per kg)'                                ,
     'Flaky fried dough in sugar glaze.',
      55000, NULL    , FALSE,   5,  170),
    ('itm_gw_dhoda_burfi_per_kg'                    , 'cat_gw_desserts'     , 'Dhoda Burfi (per kg)'                              ,
     'Grainy milk burfi with nuts.',
      55000, NULL    , FALSE,   5,  180),
    ('itm_gw_jalebi_per_kg'                         , 'cat_gw_desserts'     , 'Jalebi (per kg)'                                   ,
     'Coiled, fried and syrup-soaked.',
      55000, NULL    , TRUE ,   5,  190),
    ('itm_gw_kesar_rabri_per_kg'                    , 'cat_gw_desserts'     , 'Kesar Rabri (per kg)'                              ,
     'Reduced milk with saffron.',
      55000, NULL    , FALSE,   5,  200),
    ('itm_gw_emarti_per_kg'                         , 'cat_gw_desserts'     , 'Emarti (per kg)'                                   ,
     'Urad dal spirals in syrup.',
      56000, NULL    , FALSE,   5,  210),
    ('itm_gw_khoya_plain_burfi_per_kg'              , 'cat_gw_desserts'     , 'Khoya Plain Burfi (per kg)'                        ,
     'Plain khoya burfi.',
      56000, NULL    , FALSE,   5,  220),
    ('itm_gw_coconut_burfi_per_kg'                  , 'cat_gw_desserts'     , 'Coconut Burfi (per kg)'                            ,
     'Fresh coconut and milk.',
      58000, NULL    , FALSE,   5,  230),
    ('itm_gw_khoya_modak_per_kg'                    , 'cat_gw_desserts'     , 'Khoya Modak (per kg)'                              ,
     'Khoya shaped as modak.',
      58000, NULL    , FALSE,   5,  240),
    ('itm_gw_lauki_burfi_per_kg'                    , 'cat_gw_desserts'     , 'Lauki Burfi (per kg)'                              ,
     'Bottle gourd cooked down with khoya.',
      58000, NULL    , FALSE,   5,  250),
    ('itm_gw_paneer_jalebi_per_kg'                  , 'cat_gw_desserts'     , 'Paneer Jalebi (per kg)'                            ,
     'Chhena jalebi, softer than the classic.',
      58000, NULL    , FALSE,   5,  260),
    ('itm_gw_raskadam_per_kg'                       , 'cat_gw_desserts'     , 'Raskadam (per kg)'                                 ,
     'Rasgulla wrapped in khoya.',
      58000, NULL    , FALSE,   5,  270),
    ('itm_gw_badam_chaap_per_kg'                    , 'cat_gw_desserts'     , 'Badam Chaap (per kg)'                              ,
     'Almond sweet, by weight.',
      61000, NULL    , FALSE,   5,  280),
    ('itm_gw_besan_laddu_per_kg'                    , 'cat_gw_desserts'     , 'Besan Laddu (per kg)'                              ,
     'Roasted gram flour and ghee.',
      61000, NULL    , FALSE,   5,  290),
    ('itm_gw_dry_gulab_jamun_per_kg'                , 'cat_gw_desserts'     , 'Dry Gulab Jamun (per kg)'                          ,
     'Gulab jamun without syrup.',
      61000, NULL    , FALSE,   5,  300),
    ('itm_gw_gond_laddu_per_kg'                     , 'cat_gw_desserts'     , 'Gond Laddu (per kg)'                               ,
     'Edible gum, ghee and nuts. A winter sweet.',
      61000, NULL    , FALSE,   5,  310),
    ('itm_gw_gulab_jamun_per_kg'                    , 'cat_gw_desserts'     , 'Gulab Jamun (per kg)'                              ,
     'In syrup, by weight.',
      61000, NULL    , FALSE,   5,  320),
    ('itm_gw_jodhpuri_laddu_per_kg'                 , 'cat_gw_desserts'     , 'Jodhpuri Laddu (per kg)'                           ,
     'Boondi laddu, Jodhpur style.',
      61000, NULL    , FALSE,   5,  330),
    ('itm_gw_khoya_pista_burfi_per_kg'              , 'cat_gw_desserts'     , 'Khoya Pista Burfi (per kg)'                        ,
     'Khoya burfi with pistachio.',
      61000, NULL    , FALSE,   5,  340),
    ('itm_gw_motichoor_modak_per_kg'                , 'cat_gw_desserts'     , 'Motichoor Modak (per kg)'                          ,
     'Motichoor shaped as modak.',
      61000, NULL    , FALSE,   5,  350),
    ('itm_gw_motichur_laddu_per_kg'                 , 'cat_gw_desserts'     , 'Motichur Laddu (per kg)'                           ,
     'Fine boondi, bound with syrup.',
      61000, NULL    , FALSE,   5,  360),
    ('itm_gw_small_gulab_jamun_per_kg'              , 'cat_gw_desserts'     , 'Small Gulab Jamun (per kg)'                        ,
     'Bite-sized, in syrup.',
      61000, NULL    , FALSE,   5,  370),
    ('itm_gw_beetroot_halwa_per_kg'                 , 'cat_gw_desserts'     , 'Beetroot Halwa (per kg)'                           ,
     'Beetroot slow-cooked with ghee and khoya.',
      62000, NULL    , FALSE,   5,  380),
    ('itm_gw_gajar_halwa_seasonal_per_kg'           , 'cat_gw_desserts'     , 'Gajar Halwa (Seasonal, per kg)'                    ,
     'Carrot, ghee and khoya. Winter only.',
      62000, NULL    , TRUE ,   5,  390),
    ('itm_gw_chenna_toast_per_kg'                   , 'cat_gw_desserts'     , 'Chenna Toast (per kg)'                             ,
     'Griddled chhena, by weight.',
      63000, NULL    , FALSE,   5,  400),
    ('itm_gw_khoya_roll_per_kg'                     , 'cat_gw_desserts'     , 'Khoya Roll (per kg)'                               ,
     'Rolled khoya with nuts.',
      63000, NULL    , FALSE,   5,  410),
    ('itm_gw_makhana_burfi_per_kg'                  , 'cat_gw_desserts'     , 'Makhana Burfi (per kg)'                            ,
     'Fox nut and khoya burfi.',
      63000, NULL    , FALSE,   5,  420),
    ('itm_gw_milk_cake_per_kg'                      , 'cat_gw_desserts'     , 'Milk Cake (per kg)'                                ,
     'Grainy, caramelised milk cake.',
      63000, NULL    , TRUE ,   5,  430),
    ('itm_gw_milk_peda_per_kg'                      , 'cat_gw_desserts'     , 'Milk Peda (per kg)'                                ,
     'Soft milk peda.',
      63000, NULL    , FALSE,   5,  440),
    ('itm_gw_kalakand_per_kg'                       , 'cat_gw_desserts'     , 'Kalakand (per kg)'                                 ,
     'Moist, grainy milk sweet.',
      64000, NULL    , FALSE,   5,  450),
    ('itm_gw_moong_dal_burfi_per_kg'                , 'cat_gw_desserts'     , 'Moong Dal Burfi (per kg)'                          ,
     'Roasted moong dal and ghee.',
      64000, NULL    , FALSE,   5,  460),
    ('itm_gw_moong_dal_halwa_seasonal_per_kg'       , 'cat_gw_desserts'     , 'Moong Dal Halwa (Seasonal, per kg)'                ,
     'Slow-roasted moong dal in ghee. Winter only.',
      64000, NULL    , FALSE,   5,  470),
    ('itm_gw_plain_ghewar_per_kg'                   , 'cat_gw_desserts'     , 'Plain Ghewar (per kg)'                             ,
     'Honeycomb disc, soaked in syrup. A monsoon sweet.',
      66000, NULL    , FALSE,   5,  480),
    ('itm_gw_gujiya_per_kg'                         , 'cat_gw_desserts'     , 'Gujiya (per kg)'                                   ,
     'Pastry stuffed with khoya and nuts.',
      68000, NULL    , FALSE,   5,  490),
    ('itm_gw_chandrakala_per_kg'                    , 'cat_gw_desserts'     , 'Chandrakala (per kg)'                              ,
     'Stuffed pastry in syrup.',
      70000, NULL    , FALSE,   5,  500),
    ('itm_gw_malai_chaap_sweet_per_kg'              , 'cat_gw_desserts'     , 'Malai Chaap Sweet (per kg)'                        ,
     'Layered malai sweet, by weight.',
      70000, NULL    , FALSE,   5,  510),
    ('itm_gw_chocolate_burfi_per_kg'                , 'cat_gw_desserts'     , 'Chocolate Burfi (per kg)'                          ,
     'Two-layer chocolate and khoya.',
      71000, NULL    , FALSE,   5,  520),
    ('itm_gw_horlicks_burfi_per_kg'                 , 'cat_gw_desserts'     , 'Horlicks Burfi (per kg)'                           ,
     'Malted milk burfi.',
      71000, NULL    , FALSE,   5,  530),
    ('itm_gw_milk_mysore_pak_per_kg'                , 'cat_gw_desserts'     , 'Milk Mysore Pak (per kg)'                          ,
     'Softer Mysore pak, made with milk.',
      71000, NULL    , FALSE,   5,  540),
    ('itm_gw_mysore_pak_per_kg'                     , 'cat_gw_desserts'     , 'Mysore Pak (per kg)'                               ,
     'Gram flour, ghee and sugar.',
      71000, NULL    , FALSE,   5,  550),
    ('itm_gw_white_chocolate_burfi_per_kg'          , 'cat_gw_desserts'     , 'White Chocolate Burfi (per kg)'                    ,
     'White chocolate over khoya.',
      71000, NULL    , FALSE,   5,  560),
    ('itm_gw_khoya_ghewar_per_kg'                   , 'cat_gw_desserts'     , 'Khoya Ghewar (per kg)'                             ,
     'Ghewar topped with khoya and nuts.',
      75000, NULL    , FALSE,   5,  570),
    ('itm_gw_kaju_katli_per_kg'                     , 'cat_gw_desserts'     , 'Kaju Katli (per kg)'                               ,
     'Cashew and sugar, rolled thin and cut into diamonds.',
     108000, NULL    , TRUE ,   5,  580),
    ('itm_gw_kesar_dryfruits_ghewar_per_kg'         , 'cat_gw_desserts'     , 'Kesar Dryfruits Ghewar (per kg)'                   ,
     'Ghewar with saffron and dry fruit.',
     110000, NULL    , FALSE,   5,  590),
    ('itm_gw_dry_fruit_mango_bite_per_kg'           , 'cat_gw_desserts'     , 'Dry Fruit Mango Bite (per kg)'                     ,
     'Mango-flavoured dry fruit sweet.',
     135000, NULL    , FALSE,   5,  600),
    ('itm_gw_dry_fruits_khajur_burfi_per_kg'        , 'cat_gw_desserts'     , 'Dry Fruits Khajur Burfi (per kg)'                  ,
     'Date and nut burfi, no added sugar.',
     140000, NULL    , FALSE,   5,  610),
    ('itm_gw_kaju_kalash_per_kg'                    , 'cat_gw_desserts'     , 'Kaju Kalash (per kg)'                              ,
     'Cashew sweet, shaped as a kalash.',
     140000, NULL    , FALSE,   5,  620),
    ('itm_gw_kaju_roll_per_kg'                      , 'cat_gw_desserts'     , 'Kaju Roll (per kg)'                                ,
     'Rolled cashew sweet.',
     140000, NULL    , FALSE,   5,  630),
    ('itm_gw_dry_fruits_anjeer_per_kg'              , 'cat_gw_desserts'     , 'Dry Fruits Anjeer (per kg)'                        ,
     'Fig and nut roll.',
     149000, NULL    , FALSE,   5,  640),
    ('itm_gw_dry_fruits_khajur_per_kg'              , 'cat_gw_desserts'     , 'Dry Fruits Khajur (per kg)'                        ,
     'Date and nut roll.',
     149000, NULL    , FALSE,   5,  650),
    ('itm_gw_dry_fruits_laddu_per_kg'               , 'cat_gw_desserts'     , 'Dry Fruits Laddu (per kg)'                         ,
     'Mixed dry fruit laddu.',
     149000, NULL    , FALSE,   5,  660),
    ('itm_gw_pista_roll_per_kg'                     , 'cat_gw_desserts'     , 'Pista Roll (per kg)'                               ,
     'Rolled pistachio sweet.',
     149000, NULL    , FALSE,   5,  670)
;

-- Priced "MRP" on the board. price_minor is NOT NULL and a guessed figure would mis-bill a real
-- diner, so these are omitted. Decide a price and uncomment:
--
-- INSERT INTO gw_item VALUES
--   ('itm_gw_mineral_water',    'cat_gw_beverages', 'Mineral Water',        NULL, 0 /* paise */, NULL, FALSE, 5, 900),
--   ('itm_gw_soft_drink_250ml', 'cat_gw_beverages', 'Soft Drink (250 ml)',  NULL, 0 /* paise */, NULL, FALSE, 5, 910),
--   ('itm_gw_soft_drink_750ml', 'cat_gw_beverages', 'Soft Drink (750 ml)',  NULL, 0 /* paise */, NULL, FALSE, 5, 920);

-- ---------------------------------------------------------------------------
-- 1. Retire what is no longer on the board. Categories first, then their names freed.
-- ---------------------------------------------------------------------------
UPDATE menu_category c
SET status = 'archived', updated_at = NOW()
FROM restaurant r, gw_target t
WHERE c.restaurant_id = r.id AND r.slug = t.slug
  AND c.uid NOT IN (SELECT uid FROM gw_category)
  AND c.status <> 'archived';

/*
    Freeing the NAME, not just the uid. menu_category carries UNIQUE (restaurant_id, name) and
    menu_item carries UNIQUE (restaurant_id, category_id, name), so a retired row keeping its name
    fails the insert below and rolls back the whole transaction. Only actual collisions are
    touched, and the NOT LIKE guard makes a second run a no-op.
*/
UPDATE menu_category c
SET name = left(c.name, 53) || ' [retired]', updated_at = NOW()
FROM restaurant r, gw_target t
WHERE c.restaurant_id = r.id AND r.slug = t.slug
  AND c.uid NOT IN (SELECT uid FROM gw_category)
  AND c.name NOT LIKE '% [retired]'
  AND c.name IN (SELECT name FROM gw_category);

-- ---------------------------------------------------------------------------
-- 2. Categories.
--
-- The WHERE on DO UPDATE is a tenant guard: uid is globally unique, so without it a collision
-- with another restaurant would quietly hand this restaurant's row to someone else's menu.
-- ---------------------------------------------------------------------------
INSERT INTO menu_category (uid, restaurant_id, name, description, sort_order, status,
                           created_at, updated_at)
SELECT v.uid, r.id, v.name, v.description, v.sort_order, 'active', NOW(), NOW()
FROM restaurant r
JOIN gw_target t ON t.slug = r.slug
CROSS JOIN gw_category v
ON CONFLICT (uid) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description,
    sort_order  = EXCLUDED.sort_order,
    status      = 'active',
    updated_at  = NOW()
WHERE menu_category.restaurant_id = EXCLUDED.restaurant_id;

-- ---------------------------------------------------------------------------
-- 3. Retire the dishes that are gone, and free their names.
-- ---------------------------------------------------------------------------
UPDATE menu_item m
SET status = 'archived', is_available = FALSE, updated_at = NOW()
FROM restaurant r, gw_target t
WHERE m.restaurant_id = r.id AND r.slug = t.slug
  AND m.uid NOT IN (SELECT uid FROM gw_item)
  AND m.status <> 'archived';

UPDATE menu_item m
SET name = left(m.name, 117) || ' [retired]', updated_at = NOW()
FROM restaurant r, gw_target t
WHERE m.restaurant_id = r.id AND r.slug = t.slug
  AND m.uid NOT IN (SELECT uid FROM gw_item)
  AND m.name NOT LIKE '% [retired]'
  AND EXISTS (
      SELECT 1 FROM gw_item i
      JOIN menu_category c ON c.uid = i.category_uid AND c.restaurant_id = m.restaurant_id
      WHERE i.name = m.name AND c.id = m.category_id
  );

-- ---------------------------------------------------------------------------
-- 4. The dishes.
--
-- food_type is hardcoded 'veg' rather than carried per row. Ganeshwaram is a pure-veg house and
-- there is nothing else on the card; a per-row column would only be somewhere for a mistake to
-- hide. If they ever serve egg, this becomes a column in gw_item -- do not special-case it here.
--
-- is_available, rating_count, rating_sum, image_url and image_key are absent from DO UPDATE on
-- purpose: this file is the authority on what is on the menu and how it is described, and on
-- nothing else. spice_level IS updated, which means a re-run overwrites a correction made in the
-- admin app -- correct it here instead, or drop that one line once the kitchen has been through.
-- ---------------------------------------------------------------------------
INSERT INTO menu_item (uid, restaurant_id, category_id, name, description, price_minor,
                       food_type, spice_level, is_available, is_bestseller, prep_time_mins,
                       sort_order, status, created_at, updated_at)
SELECT v.uid, r.id, c.id, v.name, v.description, v.price_minor,
       'veg', v.spice_level, TRUE, v.is_bestseller, v.prep_time_mins,
       v.sort_order, 'active', NOW(), NOW()
FROM restaurant r
JOIN gw_target t ON t.slug = r.slug
CROSS JOIN gw_item v
JOIN menu_category c ON c.restaurant_id = r.id AND c.uid = v.category_uid
ON CONFLICT (uid) DO UPDATE SET
    category_id    = EXCLUDED.category_id,
    name           = EXCLUDED.name,
    description    = EXCLUDED.description,
    price_minor    = EXCLUDED.price_minor,
    food_type      = EXCLUDED.food_type,
    spice_level    = EXCLUDED.spice_level,
    is_bestseller  = EXCLUDED.is_bestseller,
    prep_time_mins = EXCLUDED.prep_time_mins,
    sort_order     = EXCLUDED.sort_order,
    status         = 'active',
    updated_at     = NOW()
WHERE menu_item.restaurant_id = EXCLUDED.restaurant_id;

-- ---------------------------------------------------------------------------
-- 5. Prove it landed. Counted inside the transaction and raised on a mismatch, so a partial load
-- rolls back rather than going live half-applied.
-- ---------------------------------------------------------------------------
DO $verify$
DECLARE
    rid      INT := (SELECT r.id FROM restaurant r JOIN gw_target t ON t.slug = r.slug);
    expected INT := (SELECT count(*) FROM gw_item);
    live INT; live_cats INT; retired INT; nonveg INT;
BEGIN
    SELECT count(*) INTO live      FROM menu_item     WHERE restaurant_id = rid AND status = 'active';
    SELECT count(*) INTO live_cats FROM menu_category WHERE restaurant_id = rid AND status = 'active';
    SELECT count(*) INTO retired   FROM menu_item     WHERE restaurant_id = rid AND status = 'archived';
    SELECT count(*) INTO nonveg    FROM menu_item
     WHERE restaurant_id = rid AND status = 'active' AND food_type <> 'veg';

    IF live <> expected THEN
        RAISE EXCEPTION 'expected % active dishes, found % -- rolled back, the live menu is unchanged',
            expected, live;
    END IF;

    -- A BACKSTOP, not the protection -- worth being clear about which is which.
    --
    -- The actual protection is that food_type is hardcoded 'veg' in the INSERT above, so a row
    -- flipped to non_veg by hand is corrected on the next run rather than caught here; verified
    -- by doing exactly that. This assertion therefore only fires if somebody later makes
    -- food_type a per-row column and gets a row wrong, which is precisely when it is wanted.
    -- Diners choose this restaurant for being pure veg; one wrong row is not a cosmetic error.
    IF nonveg > 0 THEN
        RAISE EXCEPTION '% non-veg dish(es) on a pure-veg menu -- rolled back', nonveg;
    END IF;

    RAISE NOTICE 'Ganeshwaram menu: % dishes across % categories, all veg (% retired).',
        live, live_cats, retired;
END
$verify$;

COMMIT;
